name: Generate test matrices pages

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the PR branch
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}  # Ensure we checkout the PR branch (not main)

      # Step 2: Set up Python
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r dashboard_matrix/requirements.txt  

      # Step 4: Run your extraction code (dashboard_matrix/pr_matrix.py)
      - name: Extract data
        run: |
          python dashboard_matrix/generate_test_matrix_data.py

      # Step 5: Check the JSON file before modification
      - name: Check JSON before modification
        run: |
          echo "Checking JSON before modification"
          cat dashboard_matrix/ocp_data.json

      # Step 6: Set Git identity for commits (to ensure we can commit and push)
      - name: Set Git identity
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      # Step 7: Check if JSON has changes before committing
      - name: Check if JSON has changes
        run: |
          git status

      # Step 8: Commit and push updated JSON to the PR branch
      - name: Commit and push updated JSON data to the PR branch
        run: |
          git add dashboard_matrix/ocp_data.json
          git commit -m "Update test matrix data" || echo "No changes to commit"
          
          # Push the changes to the same PR branch
          git push origin HEAD:${{ github.head_ref }}

      # Step 9: Check the JSON file after modification
      - name: Check JSON after modification
        run: |
          echo "Checking JSON after modification"
          cat dashboard_matrix/ocp_data.json

      # Step 10: Run HTML generation code
      - name: Generate HTML page
        run: |
          python dashboard_matrix/generate_test_matrix_ui.py

      # Step 11: Deploy the generated HTML page
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages         # The branch the action should deploy to.
          folder: dashboard_matrix/output  # The folder the action should deploy.
          token: ${{ secrets.GITHUB_TOKEN }}
