name: Generate test matrices pages

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to check out'
        default: 'main'
        required: false
        type: string
      pr_number:
        description: 'PR number to process (must be specified as a number or "all")'
        required: false
        type: string
  
jobs:
  generate-matrix:
    if: github.event_name != 'pull_request' || github.repository == 'rh-ecosystem-edge/nvidia-ci' 
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: 'workflows/test_matrix_dashboard/output'
      OLD_OCP_FILE: 'old_ocp_data.json'
      OCP_FILE: 'ocp_data.json'
    steps:
      - name: Determine PR Number
        id: determine_pr
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
              echo "Processing all PR history for merged pull request."
              echo "PR_NUMBER=all" >> "$GITHUB_OUTPUT"
          else
              if [ -z "${{ github.event.inputs.pr_number }}" ]; then
                  echo "Error: The pr_number input is required. Please specify a PR number or 'all'."
                  exit 1
              else
              echo "Using manually specified PR: ${{ github.event.inputs.pr_number }}"
              echo "PR_NUMBER=${{ github.event.inputs.pr_number }}" >> "$GITHUB_OUTPUT"
            fi
          fi

      - name: Checkout Code (PR or main branch)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.event.inputs.branch }}
          
      - name: Checkout baseline (gh-pages branch with old ocp_data.json)
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: baseline 
          sparse-checkout: |
            ${{ env.OCP_FILE }} 

      - name: Rename and move ${{ env.OCP_FILE }} to ${{ env.OLD_OCP_FILE }}
        run: |
          echo "Renaming and moving ${GITHUB_WORKSPACE}/baseline/${{ env.OCP_FILE }} to ${GITHUB_WORKSPACE}/${{ env.OLD_OCP_FILE }}"
          cp ${GITHUB_WORKSPACE}/baseline/${{ env.OCP_FILE }} ${GITHUB_WORKSPACE}/${{ env.OLD_OCP_FILE }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          pip install -r workflows/test_matrix_dashboard/requirements.txt

      - name: Run Extraction Script
        run: |
          echo "Processing PR: ${{ steps.determine_pr.outputs.PR_NUMBER }}"
          python workflows/test_matrix_dashboard/generate_test_matrix_data.py \
            --pr "${{ steps.determine_pr.outputs.PR_NUMBER }}" \
            --output_dir "${{ env.OUTPUT_DIR }}" \
            --old_data_file ${{ env.OLD_OCP_FILE }}
        
      - name: Archive ${{ env.OLD_OCP_FILE }} 
        run: |
          echo "Archiving ${{ env.OLD_OCP_FILE }} into output directory..."
          cp ${{ env.OLD_OCP_FILE }} ${{ env.OUTPUT_DIR }}/${{ env.OLD_OCP_FILE }}

      - name: Generate UI
        run: |
          echo "Generating UI using output from ${{ env.OUTPUT_DIR }}"
          python workflows/test_matrix_dashboard/generate_test_matrix_ui.py --output_dir "${{ env.OUTPUT_DIR }}"

      - name: Deploy HTML to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ${{ env.OUTPUT_DIR }}
