name: Generate test matrices pages

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r dashboard_matrix/requirements.txt

      - name: Run extraction script
        run: |
          python dashboard_matrix/generate_test_matrix_data.py

      - name: Print JSON after script
        run: |
          echo "===== ocp_data.json AFTER SCRIPT ====="
          cat dashboard_matrix/ocp_data.json || echo "File not found"

      - name: Show git diff
        run: |
          git diff
          git status

      # IMPORTANT: Pass --force to the add param so that untracked files are forcibly tracked
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update test matrix data"
          add: "--force dashboard_matrix/ocp_data.json"
          push: "true"

      - name: Print JSON after commit
        run: |
          echo "===== ocp_data.json AFTER COMMIT ====="
          cat dashboard_matrix/ocp_data.json || echo "File not found"

      - name: Generate HTML
        run: |
          python dashboard_matrix/generate_test_matrix_ui.py

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dashboard_matrix/output
          token: ${{ secrets.GITHUB_TOKEN }}
